#!/bin/bash
rm -rf results.e
rm -rf decomp
rm -rf decompscript
rm -rf nem_spread.inp
$1/tusas --input-file=test.xml --writedecomp
bash decompscript
$1/tusas --kokkos-threads=1 --input-file=test.xml --skipdecomp
bash epuscript
../exodiff -file exofile Gold.e results.e
