#!/bin/bash
rm -rf results.e
rm -rf decomp
rm -rf decompscript
rm -rf epuscript
rm -rf nem_spread.inp
$2 -n 4 $1/tusas --kokkos-num-threads=1 --input-file=kkstest.xml --writedecomp
$2 -n 1 bash decompscript
$2 -n 4 $1/tusas --kokkos-num-threads=1 --input-file=kkstest.xml --skipdecomp
$2 -n 1 bash epuscript
$2 -n 1 $1/exodiff -file exofile Gold.e results.e