#!/bin/bash
rm -rf results.e
$1/tusas --input-file=tusas.xml
###if [[ $OSTYPE == "darwin15" ]]; then
    ../exodiff -file exofile Gold.e results.e
###ielse
###i    ../exodiff -Floor=1.e-15 Gold.e results.e
###ifi