#!/bin/bash
rm -rf results.e
$2 -n 1 $1/tusas --kokkos-num-threads=1 --input-file=tusas.xml
###if [[ $OSTYPE == "darwin15" ]]; then
$2 -n 1 $1/exodiff -file exofile Gold.e results.e
###ielse
###i    ../exodiff Gold.e results.e
###ifi