#!/bin/bash
rm -rf results.e
rm -rf decomp
rm -rf decompscript
rm -rf nem_spread.inp
mpirun -np 4 $1/tusas --input-file=farzadi.xml --writedecomp
bash decompscript
mpirun -np 4 $1/tusas --input-file=farzadi.xml --skipdecomp
bash epuscript
../exodiff -f exofile Gold.e results.e 