#!/bin/bash
rm -rf results.e
rm -rf epuscript
cp decomp3/results.e.2.0 decomp/
cp decomp5/results.e.2.1 decomp/
mpirun -np 2 $1/tusas --kokkos-threads=1 --input-file=test.xml --skipdecomp --restart
bash epuscript
$1/exodiff -file exofile Gold.e results.e