#!/bin/bash
rm -rf results.e
rm -rf epuscript
cp decomp3/results.e.2.0 decomp/
cp decomp5/results.e.2.1 decomp/
$2 -n 2 $1/tusas --kokkos-num-threads=1 --input-file=test.xml --skipdecomp --restart
$2 -n 1 bash epuscript
$2 -n 1 $1/exodiff -file exofile Gold.e results.e