#!/bin/bash
rm -rf results.e
rm -rf decomp
rm -rf decompscript
rm -rf nem_spread.inp
mpirun -np 4 $1/tusas --input-file=tusas.xml --writedecomp
bash decompscript
mpirun -np 4 $1/tusas --input-file=tusas.xml --skipdecomp
if [[ $OSTYPE == "darwin15" ]]; then
    ../exodiff -file exofile Gold.e results.e
else
    ../exodiff Gold.e results.e
fi