#!/bin/bash
rm -rf results.e
rm -rf decomp
rm -rf decompscript
rm -rf nem_spread.inp
###../../tusas --input-file=tusas.xml
$2 -n 4 $1/tusas --kokkos-num-threads=1 --input-file=tusas.xml --writedecomp
$2 -n 1 bash decompscript
$2 -n 4 $1/tusas --kokkos-num-threads=1 --input-file=tusas.xml --skipdecomp
$2 -n 1 bash epuscript
###if [[ $OSTYPE == "darwin15" ]]; then
###    ../exodiff -file exofile Gold.e results.e
###else
$2 -n 1 $1/exodiff -file exofile Gold.e results.e
###fi