#!/bin/bash
rm -rf results.e
rm -rf decomp
rm -rf decompscript
rm -rf nem_spread.inp
mpirun -np 4 $1/tusas --input-file=test.xml --writedecomp
bash decompscript
mpirun -np 4 $1/tusas --kokkos-threads=1 --input-file=test.xml --skipdecomp
bash epuscript
###if [[ $OSTYPE == "darwin15" ]]; then
$1/exodiff -file=exofile Gold.e results.e
###else
###    ../exodiff Gold.e results.e
###fi