#!/bin/bash
rm -rf results.e
rm -rf decomp
cp -r decomp_gold decomp
mpirun -np 4 $1/tusas --input-file=tusas.xml --writedecomp
mpirun -np 4 $1/tusas --input-file=tusas.xml --restart --skipdecomp
bash epuscript
###if [[ $OSTYPE == "darwin15" ]]; then
    ../exodiff -f exofile Gold.e results.e
###else
###    ../exodiff Gold.e results.e
###fi