#!/bin/bash
rm -rf results.e
###../../tusas --input-file=tusas.xml
$1/tusas --input-file=tusas.xml
###if [[ $OSTYPE == "darwin15" ]]; then
$1/exodiff -file exofile Gold.e results.e
###else
###    ../exodiff Gold.e results.e
###fi