#!/bin/bash
rm -rf results.e
rm -rf decomp
rm -rf decompscript
rm -rf nem_spread.inp
mpirun -np 4 $1/tusas --input-file=tusas.xml --writedecomp
bash decompscript
mpirun -np 4 $1/tusas --input-file=tusas.xml --skipdecomp
bash epuscript
$1/exodiff -Floor 2.4e-15 Gold.e results.e