#!/bin/bash
rm -rf results.e
###../../tusas --input-file=tusas.xml
$1/tusas --kokkos-threads=1 --input-file=tpetra.xml
###if [[ $OSTYPE == "darwin15" ]]; then
###    $1/exodiff -file exofile Gold.e results.e
###else
$1/exodiff -quiet Gold.e results.e
###fi